name:                cleancoders-openchat-haskell
version:             0.1.0.0
github:              "panavtec/cleancoders_openchat_haskell"
license:             BSD3
author:              "Christian Panadero"
maintainer:          "panavtec@gmail.com"
copyright:           "2018 Christian Panadero"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/panavtec/cleancoders_openchat_haskell#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- servant-server
- text
- time
- wai
- wai-extra
- warp
- mtl
- transformers
- postgresql-simple
- hspec
- monad-logger
- bytestring
- http-api-data

library:
  source-dirs: src

executables:
  cleancoders-openchat-haskell-hs-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cleancoders-openchat-haskell

tests:
  cleancoders-openchat-haskell-hs-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cleancoders-openchat-haskell
    - hspec
    - hspec-wai
    - hspec-wai-json
    - bytestring
    - monad-logger
