version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: sample
      POSTGRES_USER: sample
      POSTGRES_DB: cleancoders_haskell
    ports:
      - 5432:5432
    volumes:
      - ./database-migrations/:/docker-entrypoint-initdb.d/

  adminer:
   image: adminer
   restart: always
   ports:
    - 8080:8080
